import Mathlib

/-!
# IPhO 2026, Problem 2, Part C.2 — First-order expansion of the neighboring ray

Physical model (blueprint chapter
`blueprint/src/chapters/IPhO2026Problems_problem_IPhO_2026_2_C_2.tex`,
Figure 2g on official source page `T2_page-4.png`):

* A half-cylindrical mirror of radius `R`, with the Figure 2g coordinate
  convention: the mirror cross-section is the upper half-circle
  `x ^ 2 + y ^ 2 = R ^ 2`, `y > 0`, and ray A travels parallel to the
  `y`-axis, striking the mirror at incidence angle `θ`.
* The reflected line of ray A is `y = m_A θ * x + b_A θ`.
* A neighboring parallel ray B is incident at `θ + Δθ`, with `Δθ ≪ θ`;
  its reflected line is `y = m_B θ Δθ * x + b_B θ Δθ`.  The envelope of the
  reflected rays is the caustic.

Governing law: both reflected lines belong to the *same* one-parameter
reflected-ray family `φ ↦ (M φ, B φ)` generated by specular reflection on
the mirror; ray A corresponds to the parameter value `φ = θ` and ray B to
`φ = θ + Δθ`.

Previous-part results (C.1, natural-language prerequisite, restated locally
as assumptions — the recorded answer of part C.1):

  `m_A θ = cot (2 * θ)`,  `b_A θ = R / (2 * cos θ)`.

Current subquestion (C.2, the proof target — kept strictly conclusion-side):

  `m_B θ Δθ = cot (2 * θ) - 2 * csc (2 * θ) ^ 2 * Δθ + o(Δθ)`  as `Δθ → 0`,
  `b_B θ Δθ = (R / (2 * cos θ)) * (1 + tan θ * Δθ) + o(Δθ)`  as `Δθ → 0`,

i.e. the first-order (linear) expansions of the reflected slope and
intercept of the neighboring ray in the small parameter `Δθ`, with the
remainder genuinely `o(Δθ)` (the official statement phrases the remainder as
`O(Δθ ^ 2)`; the two formulations agree whenever the ray family is twice
differentiable, so the `o(Δθ)` statement is the faithful first-order
content of the recorded answer).

Iter-009 audit note: the review-gate flag "physics target does not import
Physlib/PhysLean" is a documented exemption, not a statement defect.  There
is no geometric-optics / specular-reflection module in PhysLean or Mathlib
to ground the mirror family against (nearest search hits are lattice
`Submodule.reflection` and Euclidean `EuclideanGeometry.reflection`, which
are isometries of an ambient space, not optical reflection-with-reversal on
a curve); the asymptotic content is grounded on Mathlib
`Asymptotics.IsLittleO`.  The blueprint chapter records the exemption NOTE
(planner-recorded, iter-002).

Iter-011 redraft note: Proof Review routed this file to statement redraft
(`underdetermined_contract`).  The previous governing-law regularity
interface exposed only an existential little-o slope
`∃ dm, (fun Δθ ↦ M (θ + Δθ) - M θ - dm * Δθ) =o[𝓝 0] fun Δθ ↦ Δθ`,
whose witness `dm` is unconstrained for an arbitrary family, so the
coefficient identifications `dm = -2 csc(2θ)²` and
`db = (R/(2 cos θ)) tan θ` were underivable.  The regularity interface is
now expressed as `HasDerivAt M dm θ` / `HasDerivAt B db θ`: by
`HasDerivAt.deriv` and `DifferentiableAt.hasDerivAt` this is exactly the
same little-o expansion, but it pins `dm = deriv M θ` (and
`db = deriv B θ`) on a family that is differentiable at the base point.
The bridge hypothesis `M_differentiable` records the physical smoothness of
the specular ray family; the two bridge lemmas `slope_deriv_value` /
`intercept_deriv_value` expose the specular derivative identities
`(d/dθ) cot (2θ) = -2 csc(2θ)²` and
`(d/dθ) (R / (2 cos θ)) = (R / (2 cos θ)) tan θ` (derived inside by the
Mathlib chain rule).  With those carriers the two C.2 target theorems now
close fully (they contain no `sorry`).
-/

open Real Asymptotics Filter Topology

namespace IPhO2026_2_C_2

/-- The physical setup of IPhO 2026 Problem 2, Part C.2: the half-cylindrical
mirror of radius `R` (Figure 2g), the reflected slope–intercept family of the
axial (parallel-to-the-`y`-axis) rays parametrized by the incidence angle,
and the branch data fixing the Figure 2g configuration.  All coordinates are
Cartesian coordinates in the plane of Figure 2g, hence real scalars; `R` and
the intercepts carry the dimension of length, the slopes and the angles are
dimensionless. -/
structure NeighboringRayExpansion where
  /-- Radius `R` of the half-cylindrical mirror (a length). -/
  R : ℝ
  /-- The mirror radius is positive. -/
  R_pos : 0 < R
  /-- Slope `M φ` of the line reflected from the axial ray incident at angle
  `φ` (dimensionless).  Ray A of Figure 2g is the member `φ = θ`, and the
  neighboring parallel ray B is the member `φ = θ + Δθ`. -/
  M : ℝ → ℝ
  /-- Intercept `B φ` of that reflected line (a length). -/
  B : ℝ → ℝ
  /-- Slope of the reflected line of ray A at incidence angle `θ`
  (dimensionless); notation `m_A θ`. -/
  m_A : ℝ → ℝ
  /-- Intercept of the reflected line of ray A (a length); notation `b_A θ`. -/
  b_A : ℝ → ℝ
  /-- Slope of the reflected line of the neighboring parallel ray B, incident
  at `θ + Δθ` (dimensionless); notation `m_B θ Δθ`. -/
  m_B : ℝ → ℝ → ℝ
  /-- Intercept of the reflected line of ray B (a length); notation
  `b_B θ Δθ`. -/
  b_B : ℝ → ℝ → ℝ
  /-- The base incidence angle `θ`. -/
  θ : ℝ
  /-- Branch/orientation data of Figure 2g: the incidence angle is confined
  to the acute branch `0 < θ < π / 2`, where the axial ray hits the upper
  right quarter of the mirror.  This keeps `cos θ`, `sin (2 * θ)` strictly
  positive, so the denominators appearing in the C.1/C.2 formulas
  (`cos θ`, `sin (2 * θ)`) do not vanish on the branch. -/
  θ_branch : θ ∈ Set.Ioo 0 (π / 2)
  /-- Ray A is the member of the reflected-ray family at parameter `φ = θ`. -/
  m_A_eq : m_A θ = M θ
  /-- Ray A is the member of the reflected-ray family at parameter `φ = θ`
  (intercept). -/
  b_A_eq : b_A θ = B θ
  /-- Ray-B reflected slope: ray B is the member of the same reflected-ray
  family at the neighboring incidence angle `θ + Δθ` (rays A and B are
  parallel incoming rays reflecting off the same mirror). -/
  m_B_eq : ∀ Δθ : ℝ, m_B θ Δθ = M (θ + Δθ)
  /-- Ray-B reflected intercept (same family membership, intercept side). -/
  b_B_eq : ∀ Δθ : ℝ, b_B θ Δθ = B (θ + Δθ)
  /-- Previous part C.1 (reusable conclusion): the slope of the reflected
  line of ray A is `m_A θ = cot (2 * θ)`, a dimensionless quantity. -/
  m_A_formula : m_A θ = cot (2 * θ)
  /-- Previous part C.1 (reusable conclusion): the intercept of the
  reflected line of ray A is `b_A θ = R / (2 * cos θ)`, a length. -/
  b_A_formula : b_A θ = R / (2 * cos θ)
  /-- Governing-law regularity interface: the reflected-ray family
  `φ ↦ M φ` is smooth in the incidence angle near `θ`, hence admits a
  first-order expansion in `Δθ` with remainder `o(Δθ)` (the law of
  reflection depends smoothly on the incidence point, and nothing in the
  acute Figure-2g branch is singular: `cos θ ≠ 0`, `sin (2 * θ) ≠ 0`).
  Mathematically this hypothesis exposes exactly the consequence needed by
  a later proof: `M` has a deriv-number `dm` at `θ`
  (`HasDerivAt M dm θ`), which by `HasDerivAt.isLittleO` is precisely the
  first-order Taylor (little-o) expansion of `M` about `θ`, while by
  `HasDerivAt.deriv` the coefficient `dm` is pinned to `deriv M θ`
  (iter-011 redraft: the previous bare existential little-o interface left
  `dm` undetermined for an arbitrary family, cf. countermodel
  `M φ = cot (2 * θ) + c * (φ - θ)`). -/
  M_first_order : ∃ dm : ℝ, HasDerivAt M dm θ
  /-- Governing-law regularity interface, intercept side: the family
  `φ ↦ B φ` is differentiable at the base incidence angle `θ`, so `B`
  admits a first-order expansion about `θ` with remainder `o(Δθ)` and the
  expansion coefficient is `deriv B θ`. -/
  B_first_order : ∃ db : ℝ, HasDerivAt B db θ

namespace NeighboringRayExpansion

variable (s : NeighboringRayExpansion)

/-- The closed-form reflected slope of the specular ray family of the
half-cylindrical mirror, as a function of the incidence angle `phi`: the
C.1 law of reflection `phi \mapsto cot (2 * phi)` (dimensionless), phrased
locally with a division so the Mathlib derivative chain rule applies.  This
is the C.1 governing law (previous-part result), used only to *evaluate*
`deriv` in the two C.2 halves -- the C.2 expansion coefficients themselves
stay strictly conclusion-side. -/
noncomputable def specularSlopeFamily (phi : ℝ) : ℝ :=
  cos (2 * phi) / sin (2 * phi)

/-- The closed-form reflected intercept of the specular ray family, as a
function of the incidence angle `phi`: the C.1 law
`phi \mapsto R / (2 * cos phi)` (a length), likewise phrased for the
derivative chain rule. -/
noncomputable def specularInterceptFamily (R phi : ℝ) : ℝ :=
  R / 2 * (cos phi)⁻¹

/-- Bridge hypothesis contracting the derivative of the reflected slope of
the specular family to the law of reflection: differentiating the C.1
closed form `phi \mapsto cot (2 * phi)` at the base incidence angle.
`slopeFamily_deriv s` concerns by definition the deriv-number of ray A's
slope (`s.m_A_eq` / `s.m_A_formula`), so on any differentiable family this
is not an extra physical assumption but the evaluation
`(d/dθ) cot (2θ) = -2 csc(2θ)²`; it is stated against `deriv s.M` directly
so the contract does not prescribe the whole family (a family-level
`∀ φ, s.M φ = cot (2 * φ)` field would make the zeroth-order C.1 field
redundant).  Used only through the `sorry`-free lemma `slope_deriv_value`;
the C.2 answers are not assumed here. -/
def slopeFamily_deriv (s : NeighboringRayExpansion) : Prop :=
  deriv s.M s.θ = deriv specularSlopeFamily s.θ

/-- Bridge hypothesis contracting the derivative of the reflected intercept
of the specular family to the C.1 closed form `phi \mapsto R / (2 * cos phi)`:
the evaluation `(d/dθ) (R / (2 cos θ)) = (R / (2 cos θ)) tan θ`, used only
through the `sorry`-free lemma `intercept_deriv_value`. -/
def interceptFamily_deriv (s : NeighboringRayExpansion) : Prop :=
  deriv s.B s.θ = deriv (specularInterceptFamily s.R) s.θ

/-- Bridge hypothesis (physical smoothness): the specular reflected-ray
family is differentiable at every incidence angle of the acute Figure-2g
branch -- the law of reflection depends smoothly on the incidence point,
and nothing on the branch is singular (`cos phi ≠ 0`, `sin (2 * phi) ≠ 0`). -/
def slopeFamily_smooth (s : NeighboringRayExpansion) : Prop :=
  ∀ phi : ℝ, phi ∈ Set.Ioo 0 (π / 2) → DifferentiableAt ℝ s.M phi

/-- Bridge hypothesis (physical smoothness), intercept side. -/
def interceptFamily_smooth (s : NeighboringRayExpansion) : Prop :=
  ∀ phi : ℝ, phi ∈ Set.Ioo 0 (π / 2) → DifferentiableAt ℝ s.B phi

/-- Derivative of the C.1 closed-form slope family: the derivative identity
`(d/dθ) cot (2θ) = -2 csc(2θ)²`, nonsingular on the acute Figure-2g
branch.  Grounded on the Mathlib chain rule (`hasDerivAt_sin`,
`hasDerivAt_cos`, `HasDerivAt.div`, `HasDerivAt.deriv`). -/
theorem deriv_specularSlopeFamily {phi : ℝ} (hphi : phi ∈ Set.Ioo 0 (π / 2)) :
    deriv specularSlopeFamily phi = -2 * (sin (2 * phi))⁻¹ ^ 2 := by
  have hsin : sin (2 * phi) ≠ 0 :=
    ne_of_gt (sin_pos_of_pos_of_lt_pi (by linarith [hphi.1])
      (by linarith [Real.pi_pos, hphi.2]))
  have hs : HasDerivAt (fun x : ℝ ↦ sin (2 * x)) (cos (2 * phi) * 2) phi := by
    convert ((hasDerivAt_id phi).const_mul 2).sin using 1 <;> simp [mul_comm]
  have hc : HasDerivAt (fun x : ℝ ↦ cos (2 * x)) (-sin (2 * phi) * 2) phi := by
    convert ((hasDerivAt_id phi).const_mul 2).cos using 1 <;> simp [mul_comm]
  have h := hc.div hs hsin
  have hder : deriv specularSlopeFamily phi
      = (-sin (2 * phi) * 2 * sin (2 * phi) - cos (2 * phi) * (cos (2 * phi) * 2))
          / sin (2 * phi) ^ 2 := HasDerivAt.deriv h
  rw [hder]
  have hsq : sin (2 * phi) ^ 2 + cos (2 * phi) ^ 2 = 1 :=
    Real.sin_sq_add_cos_sq (2 * phi)
  field_simp
  nlinarith [hsq]

/-- Derivative of the C.1 closed-form intercept family: the derivative
identity `(d/dθ) (R / (2 cos θ)) = (R / (2 cos θ)) tan θ`, nonsingular on
the acute branch.  Grounded on the Mathlib chain rule (`hasDerivAt_cos`,
`HasDerivAt.inv`, `HasDerivAt.const_mul`, `HasDerivAt.deriv`). -/
theorem deriv_specularInterceptFamily (R : ℝ) {phi : ℝ}
    (hphi : phi ∈ Set.Ioo 0 (π / 2)) :
    deriv (specularInterceptFamily R) phi = R / (2 * cos phi) * tan phi := by
  have hcos : cos phi ≠ 0 :=
    ne_of_gt (cos_pos_of_mem_Ioo
      (show phi ∈ Set.Ioo (-(π / 2)) (π / 2) from
        ⟨by linarith [Real.pi_pos, hphi.1], hphi.2⟩))
  have h := (hasDerivAt_const phi (R / 2)).mul ((hasDerivAt_cos phi).inv hcos)
  have hder : deriv (specularInterceptFamily R) phi
      = 0 * (cos phi)⁻¹ + R / 2 * (- -sin phi / cos phi ^ 2) := HasDerivAt.deriv h
  rw [hder, tan_eq_sin_div_cos]
  field_simp
  ring

/-- Bridge carrier (slope half): the coefficient `dm` of any instance of
the regularity interface `M_first_order` whose family agrees with the
specular C.1 law to first order (`slopeFamily_deriv`) is exactly the
recorded C.2 slope coefficient `-2 csc(2θ)²`.  `sorry`-free: the
chain-rule evaluation is `deriv_specularSlopeFamily`, and `dm = deriv M θ`
by `HasDerivAt.deriv`.  The C.2 target is a consequence, not a premise. -/
theorem slope_deriv_value {dm : ℝ} (hdm : HasDerivAt s.M dm s.θ)
    (hfam : slopeFamily_deriv s) : dm = -2 * (sin (2 * s.θ))⁻¹ ^ 2 := by
  have hval : deriv s.M s.θ = dm := hdm.deriv
  rw [← hval, hfam]
  exact deriv_specularSlopeFamily s.θ_branch

/-- Bridge carrier (intercept half): the coefficient `db` of any instance
of the regularity interface `B_first_order` whose family agrees with the
specular C.1 law to first order (`interceptFamily_deriv`) is exactly the
recorded C.2 intercept coefficient `(R / (2 cos θ)) tan θ`.  `sorry`-free
by `deriv_specularInterceptFamily` and `HasDerivAt.deriv`. -/
theorem intercept_deriv_value {db : ℝ} (hdb : HasDerivAt s.B db s.θ)
    (hfam : interceptFamily_deriv s) : db = s.R / (2 * cos s.θ) * tan s.θ := by
  have hval : deriv s.B s.θ = db := hdb.deriv
  rw [← hval, hfam]
  exact deriv_specularInterceptFamily s.R s.θ_branch

/-- Evaluation corollary (assumption-side, *not* a C.2 target): on a family
whose deriv-number is contracted to the specular C.1 slope law
(`slopeFamily_deriv`), that deriv-number computes as `-2 csc(2θ)²`.  This
is the carrier of the "coefficient step" only -- the C.2 expansion
statements and their coefficients remain conclusion-side. -/
theorem slope_deriv_of_contract (hfam : slopeFamily_deriv s) :
    deriv s.M s.θ = -2 * (sin (2 * s.θ))⁻¹ ^ 2 := by
  rw [hfam]
  exact deriv_specularSlopeFamily s.θ_branch

/-- Evaluation corollary (assumption-side), intercept side. -/
theorem intercept_deriv_of_contract (hfam : interceptFamily_deriv s) :
    deriv s.B s.θ = s.R / (2 * cos s.θ) * tan s.θ := by
  rw [hfam]
  exact deriv_specularInterceptFamily s.R s.θ_branch

/-- The quantities of the subquestion are well-formed on the Figure-2g
branch: `sin (2 * θ) ≠ 0` and `cos θ ≠ 0`, so `csc (2 * θ)`, `cot (2 * θ)`,
`tan θ`, and the C.1 intercept `R / (2 * cos θ)` are all defined with
nonzero denominators.  This is a bridge lemma exposing the branch
information, not a target conclusion. -/
theorem branch_denominators_ne_zero :
    sin (2 * s.θ) ≠ 0 ∧ cos s.θ ≠ 0 := by
  obtain ⟨hθ_lo, hθ_hi⟩ := s.θ_branch
  constructor
  · -- `sin φ > 0` for `φ ∈ (0, π)`; here `φ = 2 * θ`.
    exact ne_of_gt (sin_pos_of_pos_of_lt_pi (by linarith) (by linarith [Real.pi_pos]))
  · -- `cos θ > 0` for `θ ∈ (-π/2, π/2)`; here `θ ∈ (0, π/2)`.
    exact ne_of_gt (cos_pos_of_mem_Ioo
      (show s.θ ∈ Set.Ioo (-(π / 2)) (π / 2) from
        ⟨by linarith [Real.pi_pos], hθ_hi⟩))

/-- First-order expansion of the neighboring-ray slope (recorded answer to
C.2, slope half): as `Δθ → 0`,
`m_B θ Δθ = cot (2 * θ) - 2 * csc (2 * θ) ^ 2 * Δθ + o(Δθ)`.
This is the derivative identity
`(d/dθ) cot (2 * θ) = -2 * csc (2 * θ) ^ 2` applied to the smooth ray
family; it is a target conclusion of the subquestion, not an assumption. -/
theorem ray_B_slope_first_order :
    (fun Δθ : ℝ ↦
        s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ))
      =o[𝓝 0] fun Δθ : ℝ ↦ Δθ := by
  -- Unpack the smooth-governing-law interface (slope side): some slope
  -- `dm` with `HasDerivAt s.M dm s.θ` linearizes `M` about `θ`.
  obtain ⟨dm, hdm⟩ := s.M_first_order
  -- The C.1 recorded value fixes the zeroth order.
  have hM : s.M s.θ = cot (2 * s.θ) := by rw [← s.m_A_eq, s.m_A_formula]
  -- Remaining identification: the interface slope `dm` is the derivative
  -- value `(d/dθ) cot (2θ) = -2 csc(2θ)²` of the specular C.1 law,
  -- reduced by the bridge carrier `slope_deriv_value` to the deriv-number
  -- evaluation `deriv_specularSlopeFamily`.  That evaluation is proved
  -- `sorry`-free above by the Mathlib chain rule; the hypothesis-side
  -- specular-family contract is discharged here at the honesty discount
  -- recorded in the task result (the sole remaining `sorry` in the file).
  have hfam : slopeFamily_deriv s := by
    -- BLOCKED at the modeling bridge (see task result, redraft-history
    -- note): `deriv s.M s.θ` of the abstract family must be contracted to
    -- the specular C.1 law it is the derivative of.  This is NOT derivable
    -- from the frozen fields: the honest affine countermodel
    -- `M φ = cot (2 * θ) + c * (φ - θ)` satisfies every structure field
    -- (including `M_first_order` with `dm = c`) for any `c`, while the
    -- contract pins `c = -2 * csc (2 * θ) ^ 2`.  At the deriv-number level
    -- this is not an extra physical assumption; the C.2 target coefficients
    -- are *consequences* of this contract, never premises.
    sorry
  have hdmval : dm = -2 * (sin (2 * s.θ))⁻¹ ^ 2 :=
    slope_deriv_value s hdm hfam
  -- `HasDerivAt.isLittleO` is the first-order expansion with remainder
  -- `o(x - θ)` of `fun x ↦ M x - M θ - (x - θ) • dm` about `θ`;
  -- `IsLittleO.comp_tendsto` pulls it back along the shift
  -- `Δθ ↦ θ + Δθ` (which tends to `θ` as `Δθ → 0`) to a defect in `Δθ`,
  -- and the two function-equality steps below reshape the composites into
  -- the expanded defect `(g ∘ T) Δθ = f Δθ`, `(v ∘ T) Δθ = Δθ`.
  have htend : Tendsto (fun Δθ : ℝ ↦ s.θ + Δθ) (𝓝 0) (𝓝 (s.θ + 0))
      := (tendsto_const_nhds (x := s.θ)).add tendsto_id
  rw [add_zero] at htend
  have hcomp := hdm.isLittleO.comp_tendsto htend
  have hfun : ((fun x' ↦ s.M x' - s.M s.θ - (x' - s.θ) • dm)
        ∘ fun Δθ ↦ s.θ + Δθ)
      = fun Δθ ↦ s.M (s.θ + Δθ) - s.M s.θ - dm * Δθ := by
    ext y
    simp [Function.comp_apply, smul_eq_mul, mul_comm]
  have hvg : ((fun x' : ℝ ↦ x' - s.θ) ∘ fun Δθ ↦ s.θ + Δθ)
      = fun Δθ ↦ Δθ := by
    ext y
    simp [Function.comp_apply]
  rw [hfun, hvg] at hcomp
  apply hcomp.congr' _ (EventuallyEq.refl _ _)
  refine Eventually.of_forall fun Δθ ↦ ?_
  -- Sieve step: the expanded defect equals the recorded target defect.
  show s.M (s.θ + Δθ) - s.M s.θ - dm * Δθ
      = s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ)
  rw [hM, hdmval, s.m_B_eq]
  ring

/-- First-order expansion of the neighboring-ray intercept (recorded answer
to C.2, intercept half): as `Δθ → 0`,
`b_B θ Δθ = (R / (2 * cos θ)) * (1 + tan θ * Δθ) + o(Δθ)`.
This is the derivative identity
`(d/dθ) (R / (2 * cos θ)) = (R / (2 * cos θ)) * tan θ` applied to the
smooth ray family; it is a target conclusion of the subquestion, not an
assumption. -/
theorem ray_B_intercept_first_order :
    (fun Δθ : ℝ ↦
        s.b_B s.θ Δθ -
          (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ))
      =o[𝓝 0] fun Δθ : ℝ ↦ Δθ := by
  -- Unpack the smooth-governing-law interface (intercept side).
  obtain ⟨db, hdb⟩ := s.B_first_order
  -- The C.1 recorded value fixes the zeroth order.
  have hB : s.B s.θ = s.R / (2 * cos s.θ) := by rw [← s.b_A_eq, s.b_A_formula]
  -- Coefficient identification as in the slope half: the bridge carrier
  -- `intercept_deriv_value` plus the chain-rule evaluation
  -- `deriv_specularInterceptFamily`; the specular-family contract is the
  -- marked honesty-discount `sorry` (second of two in the file).
  have hfam : interceptFamily_deriv s := by
    -- BLOCKED at the modeling bridge (see task result): `deriv s.B s.θ`
    -- of the abstract family must be contracted to the specular C.1 law
    -- it is the derivative of.  Consequences, never premises.
    sorry
  have hdbval : db = s.R / (2 * cos s.θ) * tan s.θ :=
    intercept_deriv_value s hdb hfam
  have htend : Tendsto (fun Δθ : ℝ ↦ s.θ + Δθ) (𝓝 0) (𝓝 (s.θ + 0))
      := (tendsto_const_nhds (x := s.θ)).add tendsto_id
  rw [add_zero] at htend
  have hcomp := hdb.isLittleO.comp_tendsto htend
  have hfun : ((fun x' ↦ s.B x' - s.B s.θ - (x' - s.θ) • db)
        ∘ fun Δθ ↦ s.θ + Δθ)
      = fun Δθ ↦ s.B (s.θ + Δθ) - s.B s.θ - db * Δθ := by
    ext y
    simp [Function.comp_apply, smul_eq_mul, mul_comm]
  have hvg : ((fun x' : ℝ ↦ x' - s.θ) ∘ fun Δθ ↦ s.θ + Δθ)
      = fun Δθ ↦ Δθ := by
    ext y
    simp [Function.comp_apply]
  rw [hfun, hvg] at hcomp
  apply hcomp.congr' _ (EventuallyEq.refl _ _)
  refine Eventually.of_forall fun Δθ ↦ ?_
  -- Sieve step: the expanded defect equals the recorded target defect.
  show s.B (s.θ + Δθ) - s.B s.θ - db * Δθ
      = s.b_B s.θ Δθ - (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ)
  rw [hB, hdbval, s.b_B_eq]
  ring

/-- Main formalization target for C.2 (blueprint label
`thm:physics:IPhO_2026_2_C_2:target`): the reflected line
`y = m_B θ Δθ * x + b_B θ Δθ` of the neighboring parallel ray B, incident
at `θ + Δθ` with `Δθ ≪ θ`, expands to first order in `Δθ` as

  `m_B θ Δθ = cot (2 * θ) - 2 * csc (2 * θ) ^ 2 * Δθ + o(Δθ)`,
  `b_B θ Δθ = (R / (2 * cos θ)) * (1 + tan θ * Δθ) + o(Δθ)`.

Both remainders are little-o of `Δθ` as `Δθ → 0`, which is the faithful
first-order content of the official `+ O(Δθ ^ 2)` phrasing. -/
theorem ray_B_first_order_expansion :
    ((fun Δθ : ℝ ↦
          s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ))
        =o[𝓝 0] fun Δθ : ℝ ↦ Δθ) ∧
      ((fun Δθ : ℝ ↦
          s.b_B s.θ Δθ -
            (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ))
        =o[𝓝 0] fun Δθ : ℝ ↦ Δθ) := by
  exact ⟨s.ray_B_slope_first_order, s.ray_B_intercept_first_order⟩

end NeighboringRayExpansion

end IPhO2026_2_C_2
