import Mathlib.Data.Real.Basic
import Physlib.Units.SIUnitChoices
import Ipho2026Gpt56solBlind.Shared.ExperimentalGasVapor

/-!
# IPhO 2026 Problem 4 B.4

Answer-blind formalization of the reconstruction of a vapor-pressure series
from the indexed temperature--height record.  The empirical B.3 extrapolation
and the independently modeled zero-vapor reference height are kept distinct
and are related only by an explicit bridge hypothesis.
-/

namespace Ipho2026Gpt56solBlind.ProblemIPhO2026_4_B_4

open Shared.ISQDimensions
open Shared.FiniteObservations
open Shared.AffineFit
open Shared.GasVapor

noncomputable section

/--
Source-supplied data for one nonempty Part B cooling record.  The structure
contains the prepared run, the external occurrence-indexed sensor record, and
the declared B.3 fit inputs.  It contains neither a zero-vapor reference
solution nor any inferred vapor pressure.
-/
structure SourceData (q : ℕ) where
  run : CoolingRun
  preparedRun : PreparedCoolingRun run
  observations : HeightTemperatureSeries q
  observations_run : observations.run = run
  b3FitProtocol : FitProtocol q
  heightTemperatureGraph : IndexedSeries q (ℝ × ℝ)
  b3ExtrapolatedHeight : Length

/--
The answer-free assumptions connecting the source record to the B.4 physical
model.  The B.3 fit is explicitly ordinary least squares, sensor calibration
connects each readout to its same-index physical state, and the extrapolated
height is explicitly bridged to a separately modeled zero-vapor reference.
The strict datum inequality is only the positive-pressure domain condition.
-/
def MatchesStatement {q : ℕ} (data : SourceData q)
    (idealizedZeroVaporHeight : Length) : Prop :=
  data.b3FitProtocol = ordinaryLeastSquaresProtocol q ∧
    CalibratedHeightSeriesBridge data.observations ∧
    ExtrapolatedIdealizedZeroVaporBridge data.run data.observations
      data.b3FitProtocol data.heightTemperatureGraph data.b3ExtrapolatedHeight
      idealizedZeroVaporHeight ∧
    ∀ i : Fin q,
      AdmissibleVaporDatum data.run
        (data.observations.samples i).observedTemperature
        (data.observations.samples i).observedHeight

/--
A candidate output is the exact same-occurrence temperature--vapor-pressure
series generated by some independently constrained zero-vapor reference
height.  Its `Fin q` indexing preserves order, repetitions, and multiplicity.
-/
def VaporPressureSeriesSolution {q : ℕ} (data : SourceData q)
    (series : ObservationSeries q CoolingRun VaporPressureSample
      (fun _ _ _ ↦ True)) : Prop :=
  ∃ idealizedZeroVaporHeight : Length,
    MatchesStatement data idealizedZeroVaporHeight ∧
      VaporPressureSeries data.observations data.b3FitProtocol
        data.heightTemperatureGraph data.b3ExtrapolatedHeight
        idealizedZeroVaporHeight series

/--
At every retained observation occurrence, the governing dry-air ideal-gas
equations and total/partial-pressure balance characterize the candidate vapor
pressure by the requested B.4 height formula.
-/
theorem vaporPressureSolution_iff_heightFormula {q : ℕ}
    (data : SourceData q) (idealizedZeroVaporHeight : Length)
    (hMatches : MatchesStatement data idealizedZeroVaporHeight)
    (i : Fin q) (vaporPressure : Pressure) :
    VaporPressureSolution data.run idealizedZeroVaporHeight
        (data.observations.samples i).observedTemperature
        (data.observations.samples i).observedHeight vaporPressure ↔
      0 < coordinateInSI SIUnitChoices.SI vaporPressure ∧
        coordinateInSI SIUnitChoices.SI vaporPressure =
          coordinateInSI SIUnitChoices.SI data.run.atmosphericPressure *
            (1 -
              coordinateInSI SIUnitChoices.SI data.b3ExtrapolatedHeight *
                  coordinateInSI SIUnitChoices.SI
                    (data.observations.samples i).observedTemperature /
                (coordinateInSI SIUnitChoices.SI
                    (data.observations.samples i).observedHeight *
                  coordinateInSI SIUnitChoices.SI referenceTemperature)) := by
  rcases hMatches with ⟨_, hCalibrated, hBridge, hAdmissible⟩
  have hBridge' :
      ExtrapolatedIdealizedZeroVaporBridge data.observations.run
        data.observations data.b3FitProtocol data.heightTemperatureGraph
        data.b3ExtrapolatedHeight idealizedZeroVaporHeight := by
    simpa only [data.observations_run] using hBridge
  have hAdmissible' :
      AdmissibleVaporDatum data.observations.run
        (data.observations.samples i).observedTemperature
        (data.observations.samples i).observedHeight := by
    simpa only [data.observations_run] using hAdmissible i
  simpa only [data.observations_run] using
    (calibratedReadoutVaporPressureSolution_iff_heightFormula
      data.observations data.b3FitProtocol data.heightTemperatureGraph
      data.b3ExtrapolatedHeight idealizedZeroVaporHeight vaporPressure i
      hCalibrated hBridge' hAdmissible')

/--
Whenever the source record admits the stated calibration, extrapolation, and
physical-domain bridges, it determines exactly one occurrence-indexed
temperature--vapor-pressure output series.
-/
theorem existsUnique_vaporPressureSeriesSolution {q : ℕ}
    (data : SourceData q)
    (hMatches : ∃ idealizedZeroVaporHeight : Length,
      MatchesStatement data idealizedZeroVaporHeight) :
    ∃! series : ObservationSeries q CoolingRun VaporPressureSample
        (fun _ _ _ ↦ True),
      VaporPressureSeriesSolution data series := by
  obtain ⟨idealizedZeroVaporHeight, hMatch⟩ := hMatches
  have hMatchParts := hMatch
  rcases hMatchParts with ⟨_, hCalibrated, hBridge, hAdmissible⟩
  have hBridge' :
      ExtrapolatedIdealizedZeroVaporBridge data.observations.run
        data.observations data.b3FitProtocol data.heightTemperatureGraph
        data.b3ExtrapolatedHeight idealizedZeroVaporHeight := by
    simpa only [data.observations_run] using hBridge
  have hAdmissible' : ∀ i,
      AdmissibleVaporDatum data.observations.run
        (data.observations.samples i).observedTemperature
        (data.observations.samples i).observedHeight := by
    intro i
    simpa only [data.observations_run] using hAdmissible i
  obtain ⟨series, hSeries, hSeriesUnique⟩ :=
    existsUnique_vaporPressureSeries data.observations data.b3FitProtocol
      data.heightTemperatureGraph data.b3ExtrapolatedHeight
      idealizedZeroVaporHeight hCalibrated hBridge' hAdmissible'
  refine ⟨series, ⟨idealizedZeroVaporHeight, hMatch, hSeries⟩, ?_⟩
  intro other hOther
  rcases hOther with ⟨otherIdealizedHeight, hOtherMatch, hOtherSeries⟩
  rcases hOtherMatch with ⟨_, _, hOtherBridge, _⟩
  have hHeight : otherIdealizedHeight = idealizedZeroVaporHeight :=
    hOtherBridge.2.2.2.symm.trans hBridge.2.2.2
  subst otherIdealizedHeight
  exact hSeriesUnique other hOtherSeries

end

end Ipho2026Gpt56solBlind.ProblemIPhO2026_4_B_4
