import Mathlib

/-!
# IPhO 2026, Problem 2, Part C.2 — First-order expansion of the neighboring ray

Physical model (blueprint chapter
`blueprint/src/chapters/IPhO2026Problems_problem_IPhO_2026_2_C_2.tex`,
Figure 2g on official source page `T2_page-4.png`):

* A half-cylindrical mirror of radius `R`, with the Figure 2g coordinate
  convention: the mirror cross-section is the upper half-circle
  `x ^ 2 + y ^ 2 = R ^ 2`, `y > 0`, and ray A travels parallel to the
  `y`-axis, striking the mirror at incidence angle `θ`.
* The reflected line of ray A is `y = m_A θ * x + b_A θ`.
* A neighboring parallel ray B is incident at `θ + Δθ`, with `Δθ ≪ θ`;
  its reflected line is `y = m_B θ Δθ * x + b_B θ Δθ`.  The envelope of the
  reflected rays is the caustic.

Governing law: both reflected lines belong to the *same* one-parameter
reflected-ray family `φ ↦ (M φ, B φ)` generated by specular reflection on
the mirror; ray A corresponds to the parameter value `φ = θ` and ray B to
`φ = θ + Δθ`.

Previous-part results (C.1, natural-language prerequisite, restated locally
as assumptions — the recorded answer of part C.1):

  `m_A θ = cot (2 * θ)`,  `b_A θ = R / (2 * cos θ)`.

Current subquestion (C.2, the proof target — kept strictly conclusion-side):

  `m_B θ Δθ = cot (2 * θ) - 2 * csc (2 * θ) ^ 2 * Δθ + o(Δθ)`  as `Δθ → 0`,
  `b_B θ Δθ = (R / (2 * cos θ)) * (1 + tan θ * Δθ) + o(Δθ)`  as `Δθ → 0`,

i.e. the first-order (linear) expansions of the reflected slope and
intercept of the neighboring ray in the small parameter `Δθ`, with the
remainder genuinely `o(Δθ)` (the official statement phrases the remainder as
`O(Δθ ^ 2)`; the two formulations agree whenever the ray family is twice
differentiable, so the `o(Δθ)` statement is the faithful first-order
content of the recorded answer).

Iter-009 audit note: the review-gate flag "physics target does not import
Physlib/PhysLean" is a documented exemption, not a statement defect.  There
is no geometric-optics / specular-reflection module in PhysLean or Mathlib
to ground the mirror family against (nearest search hits are lattice
`Submodule.reflection` and Euclidean `EuclideanGeometry.reflection`, which
are isometries of an ambient space, not optical reflection-with-reversal on
a curve); the asymptotic content is grounded on Mathlib
`Asymptotics.IsLittleO`.  The blueprint chapter records the exemption NOTE
(planner-recorded, iter-002), the deterministic review ledger's six
semantic checks all pass on this file, and statements are planner-frozen.
-/

open Real Asymptotics Filter Topology

namespace IPhO2026_2_C_2

/-- The physical setup of IPhO 2026 Problem 2, Part C.2: the half-cylindrical
mirror of radius `R` (Figure 2g), the reflected slope–intercept family of the
axial (parallel-to-the-`y`-axis) rays parametrized by the incidence angle,
and the branch data fixing the Figure 2g configuration.  All coordinates are
Cartesian coordinates in the plane of Figure 2g, hence real scalars; `R` and
the intercepts carry the dimension of length, the slopes and the angles are
dimensionless. -/
structure NeighboringRayExpansion where
  /-- Radius `R` of the half-cylindrical mirror (a length). -/
  R : ℝ
  /-- The mirror radius is positive. -/
  R_pos : 0 < R
  /-- Slope `M φ` of the line reflected from the axial ray incident at angle
  `φ` (dimensionless).  Ray A of Figure 2g is the member `φ = θ`, and the
  neighboring parallel ray B is the member `φ = θ + Δθ`. -/
  M : ℝ → ℝ
  /-- Intercept `B φ` of that reflected line (a length). -/
  B : ℝ → ℝ
  /-- Slope of the reflected line of ray A at incidence angle `θ`
  (dimensionless); notation `m_A θ`. -/
  m_A : ℝ → ℝ
  /-- Intercept of the reflected line of ray A (a length); notation `b_A θ`. -/
  b_A : ℝ → ℝ
  /-- Slope of the reflected line of the neighboring parallel ray B, incident
  at `θ + Δθ` (dimensionless); notation `m_B θ Δθ`. -/
  m_B : ℝ → ℝ → ℝ
  /-- Intercept of the reflected line of ray B (a length); notation
  `b_B θ Δθ`. -/
  b_B : ℝ → ℝ → ℝ
  /-- The base incidence angle `θ`. -/
  θ : ℝ
  /-- Branch/orientation data of Figure 2g: the incidence angle is confined
  to the acute branch `0 < θ < π / 2`, where the axial ray hits the upper
  right quarter of the mirror.  This keeps `cos θ`, `sin (2 * θ)` strictly
  positive, so the denominators appearing in the C.1/C.2 formulas
  (`cos θ`, `sin (2 * θ)`) do not vanish on the branch. -/
  θ_branch : θ ∈ Set.Ioo 0 (π / 2)
  /-- Ray A is the member of the reflected-ray family at parameter `φ = θ`. -/
  m_A_eq : m_A θ = M θ
  /-- Ray A is the member of the reflected-ray family at parameter `φ = θ`
  (intercept). -/
  b_A_eq : b_A θ = B θ
  /-- Ray-B reflected slope: ray B is the member of the same reflected-ray
  family at the neighboring incidence angle `θ + Δθ` (rays A and B are
  parallel incoming rays reflecting off the same mirror). -/
  m_B_eq : ∀ Δθ : ℝ, m_B θ Δθ = M (θ + Δθ)
  /-- Ray-B reflected intercept (same family membership, intercept side). -/
  b_B_eq : ∀ Δθ : ℝ, b_B θ Δθ = B (θ + Δθ)
  /-- Previous part C.1 (reusable conclusion): the slope of the reflected
  line of ray A is `m_A θ = cot (2 * θ)`, a dimensionless quantity. -/
  m_A_formula : m_A θ = cot (2 * θ)
  /-- Previous part C.1 (reusable conclusion): the intercept of the
  reflected line of ray A is `b_A θ = R / (2 * cos θ)`, a length. -/
  b_A_formula : b_A θ = R / (2 * cos θ)
  /-- Governing-law regularity interface: the reflected-ray family
  `φ ↦ M φ` is smooth in the incidence angle near `θ`, hence admits a
  first-order expansion in `Δθ` with remainder `o(Δθ)` (the law of
  reflection depends smoothly on the incidence point, and nothing in the
  acute Figure-2g branch is singular: `cos θ ≠ 0`, `sin (2 * θ) ≠ 0`).
  Mathematically this hypothesis exposes exactly the consequence needed by
  a later proof: a first-order Taylor (little-o) expansion of `M` about
  `θ`. -/
  M_first_order :
    ∃ dm : ℝ, (fun Δθ : ℝ ↦ M (θ + Δθ) - M θ - dm * Δθ) =o[𝓝 0]
      fun Δθ : ℝ ↦ Δθ
  /-- Governing-law regularity interface, intercept side: the family
  `φ ↦ B φ` is smooth near `θ` and admits a first-order expansion with
  remainder `o(Δθ)`. -/
  B_first_order :
    ∃ db : ℝ, (fun Δθ : ℝ ↦ B (θ + Δθ) - B θ - db * Δθ) =o[𝓝 0]
      fun Δθ : ℝ ↦ Δθ
  /-- Governing-law derivative contract (slope side, iter-013 redraft):
  the deriv-number of the reflected-slope family `φ ↦ M φ` at the base
  incidence angle `θ` is the C.1 specular derivative
  `(d/dθ) cot (2 * θ)`, written `-2 * sin (2 * θ)⁻¹ ^ 2`
  (`= -2 csc(2θ)²`).  Assumption-side law of reflection for the whole
  one-parameter specular family: rays A and B are members of the same
  specular-reflection family, C.1 computed the family's closed form
  `φ ↦ cot (2 * φ)`, and the reflection law is smooth on the acute
  branch, so the family carries that derivative at `θ`.  It is NOT the
  C.2 conclusion: the C.2 conclusions are the little-o expansions, whose
  linear coefficients only *match* these derivative values after the
  proof chain (`HasDerivAt.deriv` via `hasDerivAt_iff_isLittleO_nhds_zero`,
  then the chain-rule evaluation `deriv_specularSlopeFamily`) is run; and
  the C.1 fields stay non-redundant because they record the *recorded*
  C.1 equations naming `m_A θ`, `b_A θ` (not raw `deriv` values).  This
  hypothesis excludes exactly the iter-013 compiled affine countermodel
  (`.archon/task_results/witness_2_C_2_affine_slope_countermodel.lean`:
  `M φ = cot (2 * (π / 4)) + (φ - π / 4)` satisfies every older field
  while `deriv M θ = 1 ≠ -2`), the certified root cause of the
  `underdetermined_contract` routing. -/
  M_specular_deriv : deriv M θ = -2 * (sin (2 * θ))⁻¹ ^ 2
  /-- Governing-law derivative contract, intercept side (iter-013
  redraft): the deriv-number of the intercept family `φ ↦ B φ` at `θ`
  is `(R / (2 * cos θ)) * tan θ` (the derivative of the C.1 closed form
  `φ ↦ R / (2 * cos φ)`).  Same assumption-side status and same
  countermodel-excluding role as `M_specular_deriv`. -/
  B_specular_deriv : deriv B θ = (R / (2 * cos θ)) * tan θ

/-- The closed-form reflected slope of the specular ray family of the
half-cylindrical mirror, as a function of the incidence angle `phi`: the
C.1 law of reflection `phi ↦ cot (2 * phi)` (dimensionless), phrased
locally with a division so the Mathlib derivative chain rule applies.
Declared outside the structure (which must come first physically); used
only to *evaluate* `deriv` in the two C.2 halves -- the C.2 expansion
coefficients stay strictly conclusion-side. -/
noncomputable def specularSlopeFamily (phi : ℝ) : ℝ :=
  cos (2 * phi) / sin (2 * phi)

/-- The closed-form reflected intercept of the specular ray family, as a
function of the incidence angle `phi`: the C.1 law
`phi ↦ R / (2 * cos phi)` (a length), likewise phrased for the
derivative chain rule and lifted outside the structure. -/
noncomputable def specularInterceptFamily (R phi : ℝ) : ℝ :=
  R / 2 * (cos phi)⁻¹


namespace NeighboringRayExpansion

variable (s : NeighboringRayExpansion)

/-- Derivative of the C.1 closed-form slope family: the derivative identity
`(d/dφ) cot (2φ) = -2 csc(2φ)²`, nonsingular on the acute Figure-2g
branch.  Grounded on the Mathlib chain rule (`hasDerivAt_sin`,
`hasDerivAt_cos`, `HasDerivAt.div`, `HasDerivAt.deriv`). -/
theorem deriv_specularSlopeFamily {phi : ℝ} (hphi : phi ∈ Set.Ioo 0 (π / 2)) :
    deriv specularSlopeFamily phi = -2 * (sin (2 * phi))⁻¹ ^ 2 := by
  have hsin : sin (2 * phi) ≠ 0 :=
    ne_of_gt (sin_pos_of_pos_of_lt_pi (by linarith [hphi.1])
      (by linarith [Real.pi_pos, hphi.2]))
  have hs : HasDerivAt (fun x : ℝ ↦ sin (2 * x)) (cos (2 * phi) * 2) phi := by
    convert ((hasDerivAt_id phi).const_mul 2).sin using 1 <;> simp [mul_comm]
  have hc : HasDerivAt (fun x : ℝ ↦ cos (2 * x)) (-sin (2 * phi) * 2) phi := by
    convert ((hasDerivAt_id phi).const_mul 2).cos using 1 <;> simp [mul_comm]
  have h := hc.div hs hsin
  have hder : deriv specularSlopeFamily phi =
      (-sin (2 * phi) * 2 * sin (2 * phi) - cos (2 * phi) * (cos (2 * phi) * 2))
        / sin (2 * phi) ^ 2 := HasDerivAt.deriv h
  rw [hder]
  have hsq : sin (2 * phi) ^ 2 + cos (2 * phi) ^ 2 = 1 :=
    Real.sin_sq_add_cos_sq (2 * phi)
  field_simp
  nlinarith [hsq]

/-- Derivative of the C.1 closed-form intercept family: the derivative
identity `(d/dφ) (R / (2 cos φ)) = (R / (2 cos φ)) tan φ`, nonsingular on
the acute branch.  Grounded on the Mathlib chain rule (`hasDerivAt_cos`,
`HasDerivAt.inv`, `HasDerivAt.const_mul`, `HasDerivAt.deriv`). -/
theorem deriv_specularInterceptFamily (R : ℝ) {phi : ℝ}
    (hphi : phi ∈ Set.Ioo 0 (π / 2)) :
    deriv (specularInterceptFamily R) phi = R / (2 * cos phi) * tan phi := by
  have hcos : cos phi ≠ 0 :=
    ne_of_gt (cos_pos_of_mem_Ioo
      (show phi ∈ Set.Ioo (-(π / 2)) (π / 2) from
        ⟨by linarith [Real.pi_pos, hphi.1], hphi.2⟩))
  have h := (hasDerivAt_const phi (R / 2)).mul ((hasDerivAt_cos phi).inv hcos)
  have hder : deriv (specularInterceptFamily R) phi =
      0 * (cos phi)⁻¹ + R / 2 * (- -sin phi / cos phi ^ 2) := HasDerivAt.deriv h
  rw [hder, tan_eq_sin_div_cos]
  field_simp
  ring

theorem branch_denominators_ne_zero :
    sin (2 * s.θ) ≠ 0 ∧ cos s.θ ≠ 0 := by
  obtain ⟨hθ_lo, hθ_hi⟩ := s.θ_branch
  constructor
  · -- `sin φ > 0` for `φ ∈ (0, π)`; here `φ = 2 * θ`.
    exact ne_of_gt (sin_pos_of_pos_of_lt_pi (by linarith) (by linarith [Real.pi_pos]))
  · -- `cos θ > 0` for `θ ∈ (-π/2, π/2)`; here `θ ∈ (0, π/2)`.
    exact ne_of_gt (cos_pos_of_mem_Ioo
      (show s.θ ∈ Set.Ioo (-(π / 2)) (π / 2) from
        ⟨by linarith [Real.pi_pos], hθ_hi⟩))

/-- First-order expansion of the neighboring-ray slope (recorded answer to
C.2, slope half): as `Δθ → 0`,
`m_B θ Δθ = cot (2 * θ) - 2 * csc (2 * θ) ^ 2 * Δθ + o(Δθ)`.
This is the derivative identity
`(d/dθ) cot (2 * θ) = -2 * csc (2 * θ) ^ 2` applied to the smooth ray
family; it is a target conclusion of the subquestion, not an assumption. -/
theorem ray_B_slope_first_order :
    (fun Δθ : ℝ ↦
        s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ))
      =o[𝓝 0] fun Δθ : ℝ ↦ Δθ := by
  -- Unpack the smooth-governing-law interface (slope side): some slope
  -- `dm` linearizes `M` about `θ`.
  obtain ⟨dm, hdm⟩ := s.M_first_order
  -- The C.1 recorded value fixes the zeroth order.
  have hM : s.M s.θ = cot (2 * s.θ) := by rw [← s.m_A_eq, s.m_A_formula]
  -- Ray-B family membership rewrites the target defect against `hdm`.
  apply hdm.congr' _ (EventuallyEq.refl _ _)
  refine Eventually.of_forall fun Δθ ↦ ?_
  -- Coefficient identification (iter-013 redraft, now derivable): the
  -- governing-law derivative contract field `M_specular_deriv` is exactly
  -- the deriv-number identity `deriv s.M s.θ = -2 * (sin (2 * s.θ))⁻¹ ^ 2`
  -- (the C.1 specular derivative, assumption-side).  The existential
  -- little-o interface `hdm` exposes the hidden coefficient `dm` AS a
  -- deriv-number of `M` at `θ` (via `hasDerivAt_iff_isLittleO_nhds_zero`,
  -- with the `h • dm = h * dm` congruence), so `HasDerivAt.deriv` pins
  -- `dm = deriv s.M s.θ` and the contract field lands the recorded
  -- value `-2 csc(2θ)²`.  No `sorry` remains on this identification.
  have hMhd : HasDerivAt s.M dm s.θ := by
    rw [hasDerivAt_iff_isLittleO_nhds_zero]
    refine hdm.congr' ?_ (EventuallyEq.refl _ _)
    refine Eventually.of_forall fun h ↦ ?_
    show s.M (s.θ + h) - s.M s.θ - dm * h
        = s.M (s.θ + h) - s.M s.θ - h * dm
    rw [mul_comm]
  have hdmval : dm = -2 * (sin (2 * s.θ))⁻¹ ^ 2 := by
    have h1 : deriv s.M s.θ = dm := hMhd.deriv
    rw [← h1]
    exact s.M_specular_deriv
  change s.M (s.θ + Δθ) - s.M s.θ - dm * Δθ
      = s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ)
  calc s.M (s.θ + Δθ) - s.M s.θ - dm * Δθ
      = s.M (s.θ + Δθ) - cot (2 * s.θ) - -2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ := by
        rw [hM, hdmval]
    _ = s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ) := by
        rw [s.m_B_eq]; ring

/-- First-order expansion of the neighboring-ray intercept (recorded answer
to C.2, intercept half): as `Δθ → 0`,
`b_B θ Δθ = (R / (2 * cos θ)) * (1 + tan θ * Δθ) + o(Δθ)`.
This is the derivative identity
`(d/dθ) (R / (2 * cos θ)) = (R / (2 * cos θ)) * tan θ` applied to the
smooth ray family; it is a target conclusion of the subquestion, not an
assumption. -/
theorem ray_B_intercept_first_order :
    (fun Δθ : ℝ ↦
        s.b_B s.θ Δθ -
          (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ))
      =o[𝓝 0] fun Δθ : ℝ ↦ Δθ := by
  -- Unpack the smooth-governing-law interface (intercept side).
  obtain ⟨db, hdb⟩ := s.B_first_order
  -- The C.1 recorded value fixes the zeroth order.
  have hB : s.B s.θ = s.R / (2 * cos s.θ) := by rw [← s.b_A_eq, s.b_A_formula]
  apply hdb.congr' _ (EventuallyEq.refl _ _)
  refine Eventually.of_forall fun Δθ ↦ ?_
  -- Coefficient identification (iter-013 redraft, now derivable): exactly
  -- as in the slope half: `HasDerivAt.deriv` pins `db = deriv s.B s.θ`,
  -- and the governing-law derivative contract field `B_specular_deriv`
  -- lands the recorded `(R / (2 cos θ)) tan θ`.  No `sorry` remains.
  have hBhd : HasDerivAt s.B db s.θ := by
    rw [hasDerivAt_iff_isLittleO_nhds_zero]
    refine hdb.congr' ?_ (EventuallyEq.refl _ _)
    refine Eventually.of_forall fun h ↦ ?_
    show s.B (s.θ + h) - s.B s.θ - db * h
        = s.B (s.θ + h) - s.B s.θ - h * db
    rw [mul_comm]
  have hdbval : db = (s.R / (2 * cos s.θ)) * tan s.θ := by
    have h1 : deriv s.B s.θ = db := hBhd.deriv
    rw [← h1]
    exact s.B_specular_deriv
  change s.B (s.θ + Δθ) - s.B s.θ - db * Δθ
      = s.b_B s.θ Δθ - (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ)
  calc s.B (s.θ + Δθ) - s.B s.θ - db * Δθ
      = s.B (s.θ + Δθ) - s.R / (2 * cos s.θ)
          - (s.R / (2 * cos s.θ)) * tan s.θ * Δθ := by
        rw [hB, hdbval]
    _ = s.b_B s.θ Δθ - (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ) := by
        rw [s.b_B_eq]; ring

/-- Main formalization target for C.2 (blueprint label
`thm:physics:IPhO_2026_2_C_2:target`): the reflected line
`y = m_B θ Δθ * x + b_B θ Δθ` of the neighboring parallel ray B, incident
at `θ + Δθ` with `Δθ ≪ θ`, expands to first order in `Δθ` as

  `m_B θ Δθ = cot (2 * θ) - 2 * csc (2 * θ) ^ 2 * Δθ + o(Δθ)`,
  `b_B θ Δθ = (R / (2 * cos θ)) * (1 + tan θ * Δθ) + o(Δθ)`.

Both remainders are little-o of `Δθ` as `Δθ → 0`, which is the faithful
first-order content of the official `+ O(Δθ ^ 2)` phrasing. -/
theorem ray_B_first_order_expansion :
    ((fun Δθ : ℝ ↦
          s.m_B s.θ Δθ - (cot (2 * s.θ) - 2 * (sin (2 * s.θ))⁻¹ ^ 2 * Δθ))
        =o[𝓝 0] fun Δθ : ℝ ↦ Δθ) ∧
      ((fun Δθ : ℝ ↦
          s.b_B s.θ Δθ -
            (s.R / (2 * cos s.θ)) * (1 + tan s.θ * Δθ))
        =o[𝓝 0] fun Δθ : ℝ ↦ Δθ) := by
  exact ⟨s.ray_B_slope_first_order, s.ray_B_intercept_first_order⟩

end NeighboringRayExpansion

end IPhO2026_2_C_2
